const formatProfile = (dbProfile) => ({
  ...dbProfile,
  heroName: dbProfile.hero_name,
  heroClass: dbProfile.hero_class || 'None',
  realName: dbProfile.real_name,
  currentBodySprite: dbProfile.current_body_sprite || 'https://cdn.jsdelivr.net/gh/w1zinvestmentss-star/game-assets@main/new.base.body2.png',
  loginStreak: dbProfile.login_streak || 0,
  raffleTickets: dbProfile.raffle_tickets || 0,
  totalTicketsEarned: dbProfile.total_tickets_earned || 0,
  lootboxPity: dbProfile.lootbox_pity || 0,
  defeatedBosses: (dbProfile.defeated_bosses || []).map(Number),
  unlockedAchievements: dbProfile.unlocked_achievements || [],
  unlockedTitles: dbProfile.unlocked_titles || ['The Novice'],
  level: Math.floor((dbProfile.xp || 0) / 1000) + 1,
  midtermGPA: dbProfile.midterm_gpa || 0,
  finalGPA: dbProfile.final_gpa !== undefined ? dbProfile.final_gpa : null,
  uploadQuestsCompleted: dbProfile.upload_quests_completed || 0,
  quizQuestsCompleted: dbProfile.quiz_quests_completed || 0,
  multiStepQuestsCompleted: dbProfile.multi_step_quests_completed || 0,
  scenarioQuestsCompleted: dbProfile.scenario_quests_completed || 0,
  cipherQuestsCompleted: dbProfile.cipher_quests_completed || 0,
  incantationQuestsCompleted: dbProfile.incantation_quests_completed || 0,
  sportsQuestsCompleted: dbProfile.sports_quests_completed || 0,
  artsQuestsCompleted: dbProfile.arts_quests_completed || 0,
  wellnessQuestsCompleted: dbProfile.wellness_quests_completed || 0,
  journalQuestsCompleted: dbProfile.journal_quests_completed || 0,
  notifications: dbProfile.notifications || [],
  equippedPet: dbProfile.equipped_pet || null,
});

